substitutions:
  <<: !include pins-v3.yaml

packages:
  ble: !include ble.yaml
  alarms: !include alarms.yaml
  notifications: !include notifications.yaml
  music: !include music.yaml

# to be able to parse json in lambdas
json:

script:
  - id: script_update_display
    mode: restart
    then:
      - delay: 300ms
      - lambda: |-
          id(epaper).update();
  - id: script_on_page_select
    then:
      lambda: |-
        switch(id(global_page)) {
          case PAGE_HOME:
            id(global_script_control_btn_left_top_short) = nullptr;
            id(global_script_control_btn_left_top_long) = nullptr;
            id(global_script_control_btn_left_bottom_short) = nullptr;
            id(global_script_control_btn_left_bottom_long) = nullptr;

            id(global_script_control_btn_right_top_short) = nullptr;
            id(global_script_control_btn_right_top_long) = nullptr;
            id(global_script_control_btn_right_bottom_short) = nullptr;
            id(global_script_control_btn_right_bottom_long) = nullptr;
            break;
          case PAGE_MUSIC:
            id(global_script_control_btn_left_top_short) = script_music_page_btn_left_top_short;
            id(global_script_control_btn_left_top_long) = script_music_page_btn_left_top_long;
            id(global_script_control_btn_left_bottom_short) = script_music_page_btn_left_bottom_short;
            id(global_script_control_btn_left_bottom_long) = script_music_page_btn_left_bottom_long;

            id(global_script_control_btn_right_top_short) =  script_music_page_btn_right_top_short;
            id(global_script_control_btn_right_top_long) = script_music_page_btn_right_top_long;
            id(global_script_control_btn_right_bottom_short) = script_music_page_btn_right_bottom_short;
            id(global_script_control_btn_right_bottom_long) = script_music_page_btn_right_bottom_long;
            break;
          case PAGE_ALARMS:
            id(global_script_control_btn_left_top_short) = script_alarms_page_btn_left_top_short;
            id(global_script_control_btn_left_top_long) = script_alarms_page_btn_left_top_long;
            id(global_script_control_btn_left_bottom_short) = script_alarms_page_btn_left_bottom_short;
            id(global_script_control_btn_left_bottom_long) = script_alarms_page_btn_left_bottom_long;

            id(global_script_control_btn_right_top_short) =  script_alarms_page_btn_right_top_short;
            id(global_script_control_btn_right_top_long) = script_alarms_page_btn_right_top_long;
            id(global_script_control_btn_right_bottom_short) = script_alarms_page_btn_right_bottom_short;
            id(global_script_control_btn_right_bottom_long) = script_alarms_page_btn_right_bottom_long;
            break;
          case PAGE_NOTIFICATIONS:
            id(global_script_control_btn_left_top_short) = script_notifications_page_btn_left_top_short;
            id(global_script_control_btn_left_top_long) = script_notifications_page_btn_left_top_long;
            id(global_script_control_btn_left_bottom_short) = script_notifications_page_btn_left_bottom_short;
            id(global_script_control_btn_left_bottom_long) = script_notifications_page_btn_left_bottom_long;

            id(global_script_control_btn_right_top_short) =  script_notifications_page_btn_right_top_short;
            id(global_script_control_btn_right_top_long) = script_notifications_page_btn_right_top_long;
            id(global_script_control_btn_right_bottom_short) = script_notifications_page_btn_right_bottom_short;
            id(global_script_control_btn_right_bottom_long) = script_notifications_page_btn_right_bottom_long;
            break;
          default:

            id(global_script_control_btn_left_top_short) = nullptr;
            id(global_script_control_btn_left_top_long) = nullptr;
            id(global_script_control_btn_left_bottom_short) = nullptr;
            id(global_script_control_btn_left_bottom_long) = nullptr;

            id(global_script_control_btn_right_top_short) = nullptr;
            id(global_script_control_btn_right_top_long) = nullptr;
            id(global_script_control_btn_right_bottom_short) = nullptr;
            id(global_script_control_btn_right_bottom_long) = nullptr;
            break;
        }
  - id: script_page_next
    then:
      lambda: |-
        if (id(global_page) < PAGE_MAX)
          id(global_page) += 1;
          id(script_update_display).execute();

        id(script_on_page_select).execute();

  - id: script_page_prev
    then:
      lambda: |-
        if (id(global_page) > 0)
          id(global_page) -= 1;
          id(script_update_display).execute();

        id(script_on_page_select).execute();

  - id: script_vibro_short
    then:
      lambda:
        id(buzzer).turn_on();
        delay(300);
        id(buzzer).turn_off();


globals:
  - id: global_mode
    type: int
    initial_value: '0' 
  - id: global_page
    type: int
    initial_value: '0' 
  - id: global_script_control_btn_left_top_short
    type: script::SingleScript<> *
    restore_value: no
    initial_value: 'nullptr'
  - id: global_script_control_btn_left_bottom_short
    type: script::SingleScript<> *
    restore_value: no
    initial_value: 'nullptr'
  - id: global_script_control_btn_right_top_short
    type: script::SingleScript<> *
    restore_value: no
    initial_value: 'nullptr'
  - id: global_script_control_btn_right_bottom_short
    type: script::SingleScript<> *
    restore_value: no
    initial_value: 'nullptr'
  - id: global_script_control_btn_left_top_long
    type: script::SingleScript<> *
    restore_value: no
    initial_value: 'nullptr'
  - id: global_script_control_btn_left_bottom_long
    type: script::SingleScript<> *
    restore_value: no
    initial_value: 'nullptr'
  - id: global_script_control_btn_right_top_long
    type: script::SingleScript<> *
    restore_value: no
    initial_value: 'nullptr'
  - id: global_script_control_btn_right_bottom_long
    type: script::SingleScript<> *
    restore_value: no
    initial_value: 'nullptr'

esphome:
  name: watchy_minimal
  project:
    name: bobalus.watchy-ble
    version: "1.0"
  includes:
    - defs.h
  on_boot:
    then:
      - delay: 1ms
      # - pcf8563.read_time: # Only for Watchy v2
      - component.update: battery
      - component.update: epaper
      - lambda: |-
          // TODO: write me here

esp32:  
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  # https://raw.githubusercontent.com/espressif/arduino-esp32/master/tools/partitions/default_8MB.csv
  partitions: default_8MB.csv
  variant: esp32s3
  framework:
    type: esp-idf

deep_sleep:
  # https://esphome.io/components/deep_sleep.html
  wakeup_pin_mode: INVERT_WAKEUP
  wakeup_pin:
    number: $BUTTON_LEFT_TOP_PIN
    inverted: $BUTTON_PIN_INVERTED
    allow_other_uses: true

spi:
  clk_pin: ${SPI_SCK_PIN}
  mosi_pin: ${SPI_MOSI_PIN}
  miso_pin: ${SPI_MISO_PIN}

i2c:
  sda: ${I2C_SDA_PIN}
  scl: ${I2C_SCL_PIN}
  scan: false

debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  # https://esphome.io/components/sensor/index.html
  - platform: debug
    free:
      name: "Heap Free"
  # https://esphome.io/components/sensor/adc.html
  - platform: adc
    id: battery
    attenuation: auto
    pin: $BATTERY_ADC_PIN
    update_interval: never
    filters:
      - multiply: $BATTERY_VOLTAGE_DIVIDER

switch:
  # https://esphome.io/components/switch/index.html
  # https://esphome.io/components/switch/gpio.html
  # https://esphome.io/components/switch/template.html

  - platform: gpio
    id: buzzer
    pin: $VIB_MOTOR_PIN

binary_sensor:
  # https://esphome.io/components/binary_sensor
  # https://esphome.io/components/binary_sensor/gpio

  ## Upper Left ##
  - id: button_left_top_short
    pin:
      number: $BUTTON_LEFT_TOP_PIN
      allow_other_uses: true
      inverted: $BUTTON_PIN_INVERTED
    platform: gpio
    on_click:
      min_length: 0ms
      max_length: 2s
      then:
        - lambda: |-

           if (id(global_mode) == MODE_NORMAL) {
              id(script_page_prev).execute();
              return;
            }

            if( id(global_mode) == MODE_CONTROL &&
              id(global_script_control_btn_left_top_short) != nullptr) {

              id (script_vibro_short).execute();
              id(global_script_control_btn_left_top_short)->execute();
            }
            
  - id: button_left_top_long
    pin:
      number: $BUTTON_LEFT_TOP_PIN
      allow_other_uses: true
      inverted: $BUTTON_PIN_INVERTED
    platform: gpio
    filters:
      delayed_on: 3s
    on_press:
      - lambda: |-

          if (id(global_mode) == MODE_NORMAL)
            id(global_mode) = MODE_CONTROL;
          else
            id(global_mode) = MODE_NORMAL;

          id(script_update_display).execute();


          // in control mode pass-through 
          if( id(global_mode) == MODE_CONTROL &&
              id(global_script_control_btn_left_bottom_long) != nullptr) {

            id (script_vibro_short).execute();
            id(global_script_control_btn_left_top_long)->execute();
          }
          


                    
  ## Lower Left ##
  - id: button_left_bottom_short
    pin:
      number: $BUTTON_LEFT_BOTTOM_PIN
      allow_other_uses: true
      inverted: $BUTTON_PIN_INVERTED
    platform: gpio
    on_click:
      min_length: 0ms
      max_length: 2s
      then:
        - lambda: |-

            // just switch pages
            if (id(global_mode) == MODE_NORMAL) {
              id (script_vibro_short).execute();
              id(script_page_next).execute();
              return;
            }

            // in control mode pass-through 
            if( id(global_mode) == MODE_CONTROL &&
                id(global_script_control_btn_left_bottom_short) != nullptr) {

              id (script_vibro_short).execute();
              ESP_LOGI("BTN", "calling global_script_control_btn_left_bottom_short!");
              id(global_script_control_btn_left_bottom_short)->execute();
            }            

  - id: button_left_bottom_long
    pin:
      number: $BUTTON_LEFT_BOTTOM_PIN
      allow_other_uses: true
      inverted: $BUTTON_PIN_INVERTED
    platform: gpio
    filters:
      delayed_on: 3s
    on_press:
      - lambda: |-

            // in control mode pass-through 
            if( id(global_mode) == MODE_CONTROL &&
                id(global_script_control_btn_left_bottom_long) != nullptr) {

              id (script_vibro_short).execute();
              id(global_script_control_btn_left_bottom_long)->execute();
            }
          

  ## Upper Right ##

  - id: button_right_top_short
    pin:
      number: $BUTTON_RIGHT_TOP_PIN
      allow_other_uses: true
      inverted: $BUTTON_PIN_INVERTED
    platform: gpio
    on_click:
      min_length: 0ms
      max_length: 2s
      then:
        - lambda: |-
            
            if (id(global_mode) == MODE_NORMAL) {
              id(script_page_prev).execute();
              return;
            }

            // in control mode pass-through 
            if( id(global_mode) == MODE_CONTROL &&
                id(global_script_control_btn_right_top_short) != nullptr) {

              id (script_vibro_short).execute();
              id(global_script_control_btn_right_top_short)->execute();
            }

  - id: button_right_top_long
    pin:
      number: $BUTTON_RIGHT_TOP_PIN
      allow_other_uses: true
      inverted: $BUTTON_PIN_INVERTED
    platform: gpio
    filters:
      delayed_on: 3s
    on_press:
      - lambda: |-

            // in control mode pass-through 
            if( id(global_mode) == MODE_CONTROL &&
                id(global_script_control_btn_right_top_long) != nullptr) {

              id (script_vibro_short).execute();
              id(global_script_control_btn_right_top_long)->execute();
            }
          
  ## Lower Right ##

  - id: button_right_bottom_short
    pin:
      number: $BUTTON_RIGHT_BOTTOM_PIN
      allow_other_uses: true
      inverted: $BUTTON_PIN_INVERTED
    platform: gpio
    on_click:
      min_length: 0ms
      max_length: 2s
      then:
        - lambda: |-
            if (id(global_mode) == MODE_NORMAL) {
              id(script_page_next).execute();
              return;
            }

            // in control mode pass-through 
            if( id(global_mode) == MODE_CONTROL &&
                id(global_script_control_btn_right_bottom_short) != nullptr) {

              id (script_vibro_short).execute();
              id(global_script_control_btn_right_bottom_short)->execute();
            }

  - id: button_right_bottom_long
    pin:
      number: $BUTTON_RIGHT_BOTTOM_PIN
      allow_other_uses: true
      inverted: $BUTTON_PIN_INVERTED
    platform: gpio
    filters:
      delayed_on: 3s
    on_press:
      - lambda: |-

            // in control mode pass-through 
            if( id(global_mode) == MODE_CONTROL &&
                id(global_script_control_btn_right_bottom_long) != nullptr) {

              id (script_vibro_short).execute();
              id(global_script_control_btn_right_bottom_long)->execute();
            }

        
  ## Charging ##
  - id: is_charging
    pin:
      # number: $CHRG_STATUS_PIN # Does not seem to work
      number: $USB_DET_PIN
      # inverted: true
    platform: gpio
    ## This pin seems to be unstable and can flip randomly, causing too many epaper updates:
    # on_state:
    #   component.update: epaper

logger:
  level: debug

font:
  - id: ubuntumono18
    file: "gfonts://Ubuntu+Mono"
    size: 18
  - id: ubuntumono20
    file: "gfonts://Ubuntu+Mono"
    size: 20
  - id: ubuntumono22
    file: "gfonts://Ubuntu+Mono"
    size: 22
  - id: ubuntumono28
    file: "gfonts://Ubuntu+Mono"
    size: 28
  - id: ubuntumono32
    file: "gfonts://Ubuntu+Mono"
    size: 32

display:
  # Configuration for the display
  # https://esphome.io/components/display/
  # https://esphome.io/components/display/waveshare_epaper.html
  # https://www.good-display.com/product/206.html
  # https://www.e-paper-display.com/products_detail/productId=455.html
  - id: epaper
    platform: waveshare_epaper
    model: 1.54inv2
    cs_pin: $DISPLAY_CS_PIN
    dc_pin: $DISPLAY_DC_PIN
    reset_pin: $DISPLAY_RES_PIN
    busy_pin: $DISPLAY_BUSY_PIN
    update_interval: 30s
    # Problem: full_update_every does not work as expected because esphome code will do a full update on every boot up.
    # Solution: Edited `waveshare_epaper.h` and initialise to 1 instead of 0: `uint32_t at_update_{1};`
    # See: `external_components` near the bottom.
    full_update_every: 1000
    # Duration for the display reset operation. Defaults to 200ms. Setting this value to 2ms may resolve issues with newer e-Paper Driver modules (e.g. Rev 2.1).
    reset_duration: 2ms # ?????
    lambda: |-
      auto w = it.get_width();
      auto h = it.get_height();
      const auto BLACK = Color::WHITE;
      const auto WHITE = Color::BLACK;

      it.filled_rectangle(0, 0, w, h, BLACK);
      it.filled_rectangle(0, 0, w, h, WHITE);

      time_t now;
      struct tm timeinfo;
      time(&now);
      localtime_r(&now, &timeinfo);


      // top statusbar
      const char* modes[] = { MODE_NORMAL_TITLE, MODE_CONTROL_TITLE };
      const char* mode_name = modes[id(global_mode)];

      char time_buf[6];
      snprintf(time_buf, sizeof(time_buf), "%02d:%02d", timeinfo.tm_hour, timeinfo.tm_min);

      it.printf(4, 0, id(ubuntumono20), TextAlign::TOP_LEFT, "%s", mode_name);
      it.printf(w - 4, 0, id(ubuntumono20), TextAlign::TOP_RIGHT, "%s", time_buf);

      // page content
      switch(id(global_page)) {
        case PAGE_HOME:
          it.printf(w / 2, h / 2, id(ubuntumono28), TextAlign::CENTER, "HELLO FRIEND");
          break;
        case PAGE_MUSIC:
          id(script_music_page_update).execute();
          break;
        case PAGE_ALARMS:
          id(script_alarms_page_update).execute();
          break;
        case PAGE_NOTIFICATIONS:
          id(script_notifications_page_update).execute();
          break;
        default:
          it.printf(w / 2, h / 2, id(ubuntumono28), TextAlign::CENTER, "default page");
          break;
      }

      // battery status
      const int battery_max_voltage = 399;
      const int esp_min_voltage = 220;
      auto battery_percentage = max(0, min(int((int(id(battery).state * 100) - esp_min_voltage) * 100 / (battery_max_voltage - esp_min_voltage)), 100));

      const char* ble_status = "---";  // Или "C"/"D"
      if (id(global_ble_connected))
        ble_status = "BLE";

      // bottom status bar
      it.printf(4, h, id(ubuntumono20), TextAlign::BOTTOM_LEFT, "%s", ble_status);
      it.printf(w - 4, h, id(ubuntumono20), TextAlign::BOTTOM_RIGHT, "BAT: %d%%", battery_percentage);

external_components:
  # https://esphome.io/components/external_components.html
  # This project used a slightly modified module forked from the main ESPHome project.
  # The minor customisations for Watchy are:
  #  Prevent a full ePaper refresh on ESP32 boot which is not the desired behaviour for a low-power watch.
  #   https://github.com/multipolygon/esphome/commit/6407a74ff9855d515cb16fef67f90c748f9800ea
  #  Add a pubic `do_full_update()` method to trigger the full-refresh only at certain times of day - a full update clears away ghost pixels.
  #   https://github.com/multipolygon/esphome/commit/ecf116058cc4b20007126f9099f4b07f4d46b9dd
  - components: [waveshare_epaper]
    source:
      # type: local
      # path: ../esphome/esphome/components
      type: git
      url: https://github.com/multipolygon/esphome
      ref: dev

